### ISSUE TITLE
autodb only for predefined devices

### ISSUE THREAD

**Issue by horror-vacui** [rom1v/autoadb#11]
Is there any configuration options to issue a command only for a predefined (set of) device(s)? Like a config file in ~/.autoadb/?
I would like to use scrcpy with it, but I would like to connect only to my own phone, and not other devices or someone's else phone, which is connected only for charging.

I know that most people does not have the developers options enabled in their phone, and probably any other device also won't react to adb or scrcpy, but I don't want to accidentally interact with another device.

Also for different devices, there could be different commands to execute.

**Comment by rom1v** [comment]
No, there is no configuration option, your command is called for all detected devices.

But it passes the serial as argument, so just write a bash script which executes scrcpy only when the serial matches your device.

**Comment by horror-vacui** [comment]
Thanks! That's a good point!
