### ISSUE TITLE
Error when plug device

### ISSUE THREAD

**Issue by risoul** [rom1v/autoadb#18]
Scrcpy work fine when started manually, but with autoadb scrcpy -sW '{}' I get :

`Detected device b73e81b9
ERROR: Unexpected additional argument: b73e81b9`

**Comment by rom1v** [comment]
> but with autoadb scrcpy -sW '{}' I get :

Your command is wrong.

You probably want:

```bash
autoadb scrcpy -Sw -s '{}'
```
?

**Comment by risoul** [comment]
Ah! great! thank you for this unbelievable tool!
