### ISSUE TITLE
How to run autoadb on Linux ?

### ISSUE THREAD

**Issue by Jimmy-web169** [rom1v/autoadb#20]
When i run this command
```
autoadb scrcpy -s '{ }' 
```

answer:
```
bash: autoadb: command not found

```

I already install rust enviroment from https://www.rust-lang.org/tools/install

and type this command
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

```
and successfully install

i type cargo --version display below
```
cargo 1.61.0 (a028ae4 2022-04-29)
```

then download autoadb-master.zip

extract zip

and type comman below in folder which extract by zip autoadb-master.zip
```
cargo build --release
``` 
and it generated the binary in target/release/autoadb

Did i miss something in the process?

**Comment by rom1v** [comment]
> and it generated the binary in target/release/autoadb

Then execute:

```bash
target/release/autoadb scrcpy -s '{ }' 
```

**Comment by Jimmy-web169** [comment]
![Autoadb](https://user-images.githubusercontent.com/58419536/173539650-1e506693-301f-4914-bd5a-c33005f0c9f8.png)
![Screenshot from 2022-06-14 17-01-39](https://user-images.githubusercontent.com/58419536/173539697-6ae0610a-d994-4be0-a079-287d94cf483f.png)

**Comment by rom1v** [comment]
If you are already in the `autoadb` directory, execute:

```
./autoadb scrcpy -s '{}'
```

But if you are in `~/scrcpy/autoadb-master`, then execute:

```bash
target/release/autoadb scrcpy -s '{}'
```

**Comment by Jimmy-web169** [comment]
it's working now, thank you !!!
