### ISSUE TITLE
How to open only a single control window when there are multiple adb devices

### ISSUE THREAD

**Issue by shenghuang147** [rom1v/autoadb#26]
When there are two devices in my `adb devices` for example:
```
$ : adb adb devices
List of devices attached
192.168.43.10:5555 device
192.168.43.234:5555 device
```

I use `autoadb scrcpy -s 192.168.43.10:5555` 
This opens two `192.168.43.10:5555` connection windows repeatedly.

![图片](https://github.com/user-attachments/assets/f90851ef-caab-492f-a107-2bc3117da7b9)

Is this expected behavior or is there a problem?

**Comment by rom1v** [comment]
If you want to use 1 single session for a specific device, use:

```bash
scrcpy -s 192.168.43.10:5555
```

If you want to open 1 scrcpy instance for each connected device, use:

```bash
autoadb scrcpy -s '{}'
```

**Comment by shenghuang147** [comment]
> If you want to use 1 single session for a specific device, use:
> 
> ```shell
> scrcpy -s 192.168.43.10:5555
> ```
> 
> If you want to open 1 scrcpy instance for each connected device, use:
> 
> ```shell
> autoadb scrcpy -s '{}'
> ```

Well, thank you
