### ISSUE TITLE
scrcpy: dyld: Library not loaded on macOS Catalina

### ISSUE THREAD

**Issue by Skaldebane** [rom1v/autoadb#6]
Hi.

I compiled the latest version of this repo using `cargo` on macOS Catalina.
I have two devices: An AVD (Emulator) and a physical Android device (Samsung Galaxy J5 (2017) w/ Android 9.0).
When I start autoadb with scrcpy as you mentioned, the emulator shows up, but the phone doesn't. Showing this error:

```
Deteted device 5200b231bc27549d
2020-05-31 23:56:48.742 scrcpy[54954:174355] INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/local/Cellar/scrcpy/1.12.1/share/...shed. 3.2 MB/s (26202 bytes in 0.008s)
bind: Address already in use
```

This is very common and I usually fix it by killing adb.

When I unplug it and plug it again, it shows the following message:

```
Deteted device 5200b231bc27549d
dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/opt/p11-kit/lib/libp11-kit.0.dylib
  Reason: image not found
```

Any explanations, fixes, or workarounds?
(btw, I kept your typo 'deteted'. Consider merging my pull request)

**Comment by Skaldebane** [comment]
By the way, I have another machine with Ubuntu 20.04 and autoadb works there without problems. I open the emulator and plug my device in the same time and everything works seamlessly.

**Comment by Skaldebane** [comment]
Apparently, this problem is present in all scrcpy instances. I turned out to have an old version of scrcpy and Homebrew didn't complete its updates either. Updating everything fixed the problem!

**Comment by rom1v** [comment]
> bind: Address already in use

Yes, this shouldn't happen anymore since scrcpy v1.13: #951
